#!/usr/bin/env bash
# Resend email setup for RemoteMatch team invites
set -e

echo "=============================================="
echo " Resend email for RemoteMatch invites"
echo "=============================================="
echo ""
echo "STEP 1 — Create Resend account"
echo "  https://resend.com → Sign up (free tier: 100 emails/day)"
echo ""
echo "STEP 2 — Create API key"
echo "  Resend dashboard → API Keys → Create API Key"
echo "  Name: remotematch-production"
echo "  Permission: Sending access"
echo "  Copy the key (starts with re_)"
echo ""
echo "STEP 3 — Quick test (no domain verification)"
echo "  Use Resend's sandbox sender:"
echo "    EMAIL_FROM=RemoteMatch <onboarding@resend.dev>"
echo "  Note: sandbox only delivers to the email you signed up with."
echo ""
echo "STEP 4 — Production (send to anyone)"
echo "  Resend → Domains → Add remotematch.app"
echo "  Add the DNS records Resend shows (in your domain registrar)"
echo "  After verified, set:"
echo "    EMAIL_FROM=RemoteMatch <noreply@remotematch.app>"
echo ""
echo "STEP 5 — Paste on Render"
echo "  dashboard.render.com → remotematch → Environment"
echo "  RESEND_API_KEY = re_..."
echo "  EMAIL_FROM     = RemoteMatch <noreply@remotematch.app>"
echo "  Save → redeploy"
echo ""
echo "STEP 6 — Verify"
echo "  https://remotematch.onrender.com/api/health"
echo "  emailConfigured: true"
echo ""
echo "STEP 7 — Test invite"
echo "  Team access → Create account → check invitee inbox"
echo ""
open "https://resend.com/api-keys" 2>/dev/null || true
open "https://dashboard.render.com" 2>/dev/null || true
