#!/usr/bin/env bash
# Custom domain setup for remotelymatch on Render
# Target domain: remotelymatch.app (canonical — not remotematch.app)
set -e

DOMAIN="${1:-remotelymatch.app}"
WWW="www.${DOMAIN}"
RENDER_CNAME="remotematch.onrender.com"

echo "=============================================="
echo " remotelymatch custom domain: ${DOMAIN}"
echo "=============================================="
echo ""
echo "STEP 1 — Buy the domain"
echo "  Go to: https://www.cloudflare.com/products/registrar/"
echo "  Or:    https://www.namecheap.com"
echo "  Search: ${DOMAIN}"
echo "  (remotematch.com is already taken — use .app or .io)"
echo ""
echo "STEP 2 — Add domain in Render"
echo "  1. https://dashboard.render.com → remotelymatch service"
echo "  2. Settings → Custom Domains → Add Custom Domain"
echo "  3. Enter: ${DOMAIN}"
echo "  4. Also add: ${WWW} (optional)"
echo "  5. Copy the DNS records Render shows you"
echo ""
echo "STEP 3 — DNS records (typical Cloudflare setup)"
echo "  Type    Name    Content"
echo "  CNAME   @       ${RENDER_CNAME}"
echo "  CNAME   www     ${RENDER_CNAME}"
echo ""
echo "  In Cloudflare: set SSL/TLS to Full"
echo "  Proxy: orange cloud ON is fine"
echo ""
echo "STEP 4 — Update Render Environment variables"
echo "  APP_URL=https://${DOMAIN}"
echo "  CLIENT_ORIGIN=https://${DOMAIN},https://${RENDER_CNAME}"
echo "  CUSTOM_DOMAIN=${DOMAIN}"
echo ""
echo "STEP 5 — Redeploy"
echo "  Render redeploys automatically when env vars change."
echo "  Wait 5-10 min for DNS + SSL."
echo ""
echo "STEP 6 — Verify"
echo "  https://${DOMAIN}/api/health"
echo "  https://${DOMAIN}/welcome  (public landing page)"
echo ""
echo "STEP 7 — Chrome extension"
echo "  Profile → Connect extension automatically"
echo "  (extension already supports ${DOMAIN})"
echo ""
echo "Opening Render dashboard..."
open "https://dashboard.render.com" 2>/dev/null || true
open "https://www.cloudflare.com/products/registrar/" 2>/dev/null || true
