#!/usr/bin/env bash
# MongoDB Atlas → Render production setup checklist
set -e

echo "=============================================="
echo " MongoDB Atlas for remotelymatch (production)"
echo "=============================================="
echo ""
echo "STEP 1 — Create free cluster"
echo "  https://cloud.mongodb.com → Build a Database → M0 FREE"
echo "  Name cluster: remotelymatch"
echo "  Region: closest to Oregon (Render US-West)"
echo ""
echo "STEP 2 — Database user"
echo "  Database Access → Add New Database User"
echo "  Username: remotelymatch"
echo "  Password: (generate strong, save it)"
echo "  Role: Atlas admin OR readWrite on remotelymatch db"
echo ""
echo "STEP 3 — Network access"
echo "  Network Access → Add IP Address → Allow Access from Anywhere"
echo "  0.0.0.0/0  (required for Render)"
echo ""
echo "STEP 4 — Connection string"
echo "  Database → Connect → Drivers → Node.js"
echo "  Copy: mongodb+srv://remotematch:<PASSWORD>@cluster....mongodb.net/remotelymatch"
echo ""
echo "STEP 5 — Paste on Render"
echo "  dashboard.render.com → remotelymatch → Environment"
echo "  MONGODB_URI = (paste connection string)"
echo "  Save → wait for redeploy"
echo ""
echo "STEP 6 — Verify"
echo "  https://remotematch.onrender.com/api/health"
echo "  mongoConfigured: true"
echo ""
echo "STEP 7 — Re-login on production"
echo "  Log out → log in → Connect tab should work (no red MongoDB error)"
echo ""
open "https://cloud.mongodb.com" 2>/dev/null || true
open "https://dashboard.render.com" 2>/dev/null || true
